Added CODE_OF_CONDUCT, CONTRIBUTING, Updated README
the-guild-org/Stack pull request #9
Opened 2021-01-18 09:38 UTC by tvvignesh

As discussed, this is a small PR contains a basic onboarding workflow for new contributors with a contributing, code of conduct and references.

I have also made a 30 minute video in relation to this like you suggested. Do you have a Youtube channel for The Guild? I was not sure, so uploaded it to my drive. You can find it here. Feel free to upload it anywhere or if there is no specific channel, I can upload it on Youtube and share the link with you: https://drive.google.com/file/d/1tzEp3fxS1i_kkweg0tcoJI923F7uNYgo/view?usp=sharing

The code of conduct is adapted without any changes from [contributor covenant](https://www.contributor-covenant.org/) and the rest has been written by me.

Some things which I deliberately did not add is the commit conventions (since I was not sure if you were following any) and also the process of becoming a maintainer from a contributor (which I was not sure about again).

**CC:** @Urigo @dotansimha

2021-01-18 09:40 UTC, tvvignesh commented
One more thing to note is that [INSERT CONTACT METHOD] in CODE_OF_CONDUCT would need to be updated with the relevant contact email. I have left it as is since I did not know the email to give there.

2021-01-20 16:23 UTC, Urigo requested changes
Thank you so much!  I'm so excited for this!
Also if I was to merge everything as is, together with the video right now, it would be a huge improvement already, very nice and high quality work!

Even so, I've made comments on the text, and also here are some notes about the video:


1. My idea for the video was that you will actually show hands on example of all these steps.  For that you should actually find a real issue on one of the repos, go through a process of searching for it, finding an open issue and then taking it step by step all the way for a fix!  I've mentioned that to @dotansimha so if you can't find a good example, he will try to come up with an open issue for you to do that process with.
2. That would be in addition to the great overview and everything you've done already in the video
3. Split the video into smaller chunks by subject and we'll add those as a playlist to Youtube.  That way we could update and improve parts of it more easily while also link to specific video next to each step in the doc
4. As you will dive into each step in detail with a real demonstration, you could do a quicker overview of the steps at the start and then go deeper into each one and walk through an example of that step
5. Same will go for showing the tools as you are using - an overview as you've done, but each of them would actually be demonstrated and talked about while you demonstrate going through the steps (CI once you submit a PR with a test, docusarous when contributing to the docs etc...)
6. Could you create somewhere (maybe in the description of this PR) a checklist with all the things to do once it would be merged? for example adding a checkbox for all those steps on the Github issue/PR templates on all our repos

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- Start working on all the action items one at a time following a typical Git workflow.
Add step before about creating a reproduction

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +  - Fork the repo
I would first take a step for creating a failing test.
Later you will explain the technicalities of how to do it (fork, clone etc..)

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- Start searching the web (Google, Github, Stackoverflow, Docs, etc.) to see if you can find similar issues or solutions online
and add a step of how to contribute to the docs

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- Update the config files to reflect new versions of the packages to facilitate the build tool for releasing new versions once the PR is merged
Add all the technical details on how to do each step like that

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- Update the config files to reflect new versions of the packages to facilitate the build tool for releasing new versions once the PR is merged
maybe each step could be bold and under it would be the description on how to do it and other extra information

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [Bob](https://github.com/kamilkisiela/bob) which is a bundler allowing you to package and publish scoped packages under an organization scope. Bob makes use of [Rollup](https://rollupj
I would add a high level sentence about what Bob the bundler is doing compared to just Rollup

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [ESLint](https://eslint.org/) for maintaining sanity across all our projects with appropriate linting rules setup. You can find the rules in the `.eslintrc.json` file in the root of ev
are all repos share similar rules?

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [Prettier](https://prettier.io/) for maintaining all the formatting we need in our codebase. You can find the config setup in the `.prettierrc` file in the root of every repository
also mention that we use tools to automatically run those before commits

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +Improve the WhatsApp clone tutorial
links to everything here

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [Renovate](https://github.com/renovatebot/renovate) to keep all our dependencies updated with the latest compatible upstream versions with automerge enabled for minor versions.
I want to add that we highly recommend for people to use it on their projects as well

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +All projects maintained by The Guild makes use of these tooling to take care of the most important parts of the workflow.
We highly recommend you use these tools with your projects as well or that if you know better ones, let us know!

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- You get into trouble with the existing implementation or have an idea for a possible enhancement.
add step - make sure the same issue happens also if you update to the latest version of the library

2021-01-20 16:23 UTC, Urigo commented on CONTRIBUTING.md
> +- Spread the word about us - Tell people about our libraries and our services, create guides and tutorials
Keep all your dependencies up to date with the latest versions. 
It would help you and also help us with good feedback

2021-01-20 17:32 UTC, tvvignesh commented
Hi. Thanks for the feedback. Will update the PR and video with the changes and let you know.

2021-01-22 11:51 UTC, tvvignesh commented on CONTRIBUTING.md
> +Please help us keep all our projects open and inclusive. Kindly follow our [Code of Conduct](./CODE_OF_CONDUCT.md) derived from [Contributor Covenant](https://www.contributor-covenant.org/) to keep t
Sure. Will do it after this PR gets merged and all the projects link to this code of conduct.

2021-01-22 12:30 UTC, tvvignesh commented on CONTRIBUTING.md
> +- Update the config files to reflect new versions of the packages to facilitate the build tool for releasing new versions once the PR is merged
This might make the file look very lengthy and make this sound like a tutorial. I will instead link to the relevant external links to each step which is more detailed with screemshots and videos. Hope that works.

2021-01-22 12:41 UTC, tvvignesh commented on CONTRIBUTING.md
> +We make use of [ESLint](https://eslint.org/) for maintaining sanity across all our projects with appropriate linting rules setup. You can find the rules in the `.eslintrc.json` file in the root of ev
I had a look. There are minor variations but otherwise they all are the same.

https://github.com/ardatan/graphql-tools/blob/master/.eslintrc.json
https://github.com/dotansimha/graphql-code-generator/blob/master/.eslintrc.json
https://github.com/Urigo/graphql-mesh/blob/master/.eslintrc.json

2021-01-22 12:52 UTC, tvvignesh commented
@Urigo Made all the changes as you had mentioned. Will redo the video sometime this week based on your suggestions and share it across.

Once this PR is merged, I will send a PR to the README of all repos linking to this and will then update the contributor covenant repo adopters section as well.

2021-01-22 13:08 UTC, tvvignesh commented
> * My idea for the video was that you will actually show hands on example of all these steps.  For that you should actually find a real issue on one of the repos, go through a process of searching for it, finding an open issue and then taking it step by step all the way for a fix!  I've mentioned that to @dotansimha so if you can't find a good example, he will try to come up with an open issue for you to do that process with.

> * That would be in addition to the great overview and everything you've done already in the video

> * Split the video into smaller chunks by subject and we'll add those as a playlist to Youtube.  That way we could update and improve parts of it more easily while also link to specific video next to each step in the doc

> * As you will dive into each step in detail with a real demonstration, you could do a quicker overview of the steps at the start and then go deeper into each one and walk through an example of that step

> * Same will go for showing the tools as you are using - an overview as you've done, but each of them would actually be demonstrated and talked about while you demonstrate going through the steps (CI once you submit a PR with a test, docusarous when contributing to the docs etc...)

Got it. Will re-do the video solving the issue as you mentioned, split it into chunks and share it across.

> * Could you create somewhere (maybe in the description of this PR) a checklist with all the things to do once it would be merged? for example adding a checkbox for all those steps on the Github issue/PR templates on all our repos

Editer the PR with a checklist of things to be done.

2021-01-22 15:23 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [ESLint](https://eslint.org/) for maintaining sanity across all our projects with appropriate linting rules setup. You can find the rules in the `.eslintrc.json` file in the root of ev
@dotansimha do you think we should share and align somehow things between repos?
and also how?
maybe we could have a Guild template repo?

2021-01-22 15:27 UTC, Urigo commented on CONTRIBUTING.md
> +- Update the config files to reflect new versions of the packages to facilitate the build tool for releasing new versions once the PR is merged
good point @tvvignesh
I think you are right that a first list that is simple is good.
But I actually like the fast that this would also be a tutorial for how to contribute (with text and video steps). 
So maybe it will have first a list, with internal links to another place (tutorial step) at the bottom of the doc with the full explanation and a video?

2021-01-22 15:30 UTC, Urigo commented
please also add to the checklist some like:

- [ ] Create a labeling system that shows which step each issue is

My idea is that we could maybe ask people to triage issues according to the step the issue is currently at and maybe even have a bot commenting on an open issue asking people to advance the issue to next steps

2021-01-22 15:51 UTC, Urigo requested changes
another awesome work!
added some small things.

Can't wait to see all of it in the wild!

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +8. Once the issue is filed, we will triage it and have discussions around it suggesting the possible next steps or action items labelling the issue appropriately
I think we can remove 8 no?

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +    - Kindly provide instructions if any in the repository along with expected and actual behavior and a link back to the issue and any instructions/steps to running the repro locally.
also a short video/screencast would be very helpful

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +11. Creating failing tests are [really important](https://kentcdodds.com/blog/make-your-test-fail) when you contribute to the source since it increases the confidence on the system. Try to create a s
I would maybe write more like: A next step after a reproduction is a failing test inside the library.
That step is maybe the more helpful of them all.
Follow the instructions on how to clone the repo, run tests locally, find a new case that covers your scenario, make sure it fails and submit it as a pull request

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +12. Start working on all the action items one at a time following a typical Git workflow.
step 12-21 could be moved into the actual tutorial as it's a technical process to follow when you are trying to make steps.

I would change it to a step about creating a failing test (already there at step 11), then a step for trying to fix the test and sending a pull request, following a step on testing it locally with your own code following a step to update your software to the latest version once the pull request is merged and released as a full version to npm

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +We make use of [Bob](https://github.com/kamilkisiela/bob) which is a bundler allowing you to package and publish scoped packages under an organization scope. Bob makes use of [Rollup](https://rollupj
name it "Bob the bundler" instead of "Bob" only in the first time you mention Bob

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +In addition to what rollup does, Bob also takes care of doing things like validating `package.json` files, glob through a YARN workspace so that all files can be packaged together as scoped packages,
"...bob also takes care of common and important tasks like..."

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +## Ways you can contribute
"Ways to contribute other then code"

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +- Spread the word [about us](https://the-guild.dev/about-us) - Tell people about our libraries and our services, create guides and tutorials
guides, blog posts and tutorial

2021-01-22 15:51 UTC, Urigo commented on CONTRIBUTING.md
> +- Create failing tests and reproducible projects
link to the step above

2021-01-22 16:14 UTC, Urigo commented
ohh I also forgot to mention that the steps are not only about something failing but also about a new feature, so maybe the wording needs to make sure we also address that

2021-01-24 13:12 UTC, tvvignesh commented on CONTRIBUTING.md
> +    - Kindly provide instructions if any in the repository along with expected and actual behavior and a link back to the issue and any instructions/steps to running the repro locally.
Sure. Will take up videos/screencasts after the rest of the changes in this PR are merged/finalized.

2021-01-24 13:20 UTC, tvvignesh commented on CONTRIBUTING.md
> +12. Start working on all the action items one at a time following a typical Git workflow.
@Urigo Not sure if I am understanding you properly, but are you saying that you want to move this to the video walkthrough rather than having it as text?

2021-01-24 20:59 UTC, Urigo commented on CONTRIBUTING.md
> +12. Start working on all the action items one at a time following a typical Git workflow.
no I mean both, having a text section that walks through how to technically do those things, but as a separate and more detailed section explaining how to change the library's code

2021-01-31 11:54 UTC, tvvignesh commented
@Urigo 2nd video in the playlist: https://drive.google.com/file/d/1mW-FvS4vCCd0sfeFz083wO60WcgLsy3C/view?usp=sharing

The first would be the one which I shared before. Working on the 3rd.

2021-02-03 11:39 UTC, Urigo commented
@tvvignesh that's awesome!

can't wait for the next one :)

2021-02-09 14:25 UTC, tvvignesh commented
@Urigo Have completed the next video explaining the complete workflow with sourcecode: https://drive.google.com/file/d/1ijYH9IFVQpclqeC39Xa1hzN7xWkAZ1mg/view?usp=sharing

Relevant PR: https://github.com/dotansimha/graphql-code-generator/pull/5523

2021-02-11 13:39 UTC, Urigo commented
great video!

Just a small very not important thing and we could edit later on:   When checking the local changes with your own files, you can/should use yarn to point to your local fork instead of coping the changes to your local node_modules, it's much less error prone

2021-02-11 15:22 UTC, tvvignesh commented
> local changes with your own files, you can/should use yarn to point to your local fork instead of coping the changes to your loc

@Urigo True 👍 I am thinking of making one more video soon to demonstrate things like fixing the duplication issue, contributing to the docs/blog, and anything else I would have missed out. I will demonstate this as well when I do that.

2021-02-12 17:41 UTC, tvvignesh commented
@Urigo There are 4 things blocking to close this issue.

- Merging this PR. I had already linked the contributing and code of conduct file in this PR and sent PRs to all the respective repos most of which have been merged. Right now it will show 404 till this is merged.
- Regarding the labelling system, I have not done that since I wanted to leave that to you guys on how you want to organize all the issues since you guys know your workflow better
- And once this PR is merged, I will send a PR to contributor covenant adding all the guild repos to their list.
- Finally when I get time I will be making one more video as part of the series (probably tomorrow). If the videos so far made sense, you might want to upload them to youtube or some place so that the relevant links can be added to the contributing guide.

2021-02-16 12:03 UTC, merged

2021-02-16 12:03 UTC, ardatan commented
I merged this one to fix 404 in other repos.

2021-02-17 13:32 UTC, tvvignesh commented
@Urigo Have sent a PR to the contributor covenant repo: https://github.com/ContributorCovenant/contributor_covenant/pull/916

2021-02-18 12:36 UTC, tvvignesh commented
Last video added here: https://drive.google.com/file/d/1xp-9aPrAUv6g0ShXvxHq4PIS_dyz2mjT/view?usp=sharing

2021-02-23 00:08 UTC, Madsadglad approved these changes

2021-02-23 16:21 UTC, Madsadglad approved these changes
Good